### ISSUE TITLE
Boxun: search doesn't work

### ISSUE THREAD

**Issue by greatfire-martin** [Behemouth/website-mirror-by-proxy#2]
Try searching for any keyword.

**Comment by Behemouth** [comment]
Test pass in local,but  it return empty response in server. :cry:

**Comment by Behemouth** [comment]
It is caused by HTTP referer header. Seems source site boxun ignored search request with incorret referer.

**Comment by Behemouth** [comment]
InSite search works.
Site search with google works too but it's not the intented behavior.Because the search site becames current mirror site domain,e.g. `TEST site:d1f6fn7t4t4u3z.cloudfront.net/`, I think this should be fixed the next refactoring version too.

**Comment by greatfire-martin** [comment]
I still get blank pages for all searches. I remember I got this working before by rewriting the referer header indeed. So why is it not working now?

**Comment by greatfire-martin** [comment]
BTW, can you give me higher access to this repo so I can reopen, label issues etc

**Comment by Behemouth** [comment]
I've searched `referer` in source code before I made this commit,I have not found it so I add it to `ProxyHttpRequest::getHeaders`.

It works in chrome,now I find it's broken in firefox.

**Comment by greatfire-martin** [comment]
It doesn't manually add the referer header. It forwards all headers, except those explicitly ignored. See my comment on https://github.com/Behemouth/website-mirror-by-proxy/commit/ddc093269e5c6fcf558e95fc037f02024830b1a1. BTW, do you get alerts for comments on commits? I also added one to https://github.com/Behemouth/website-mirror-by-proxy/commit/be6423ac241a8adabcc79326fd68b85dd557fdc0.

**Comment by greatfire-martin** [comment]
nice
